Add Phytron VSS 80.200.5
paulscherrerinstitute/ecmccfg pull request #192
Opened 2023-09-13 15:17 UTC by cdn-lnk

2023-09-13 20:39 UTC, anderssandstrom commented
Wrong motor type description in headers: VSS-52.200.2.5 but should be VSS-80.200.5

2023-09-13 21:36 UTC, kivel requested changes
as per comment from @anderssandstrom

2023-09-13 21:36 UTC, kivel commented on hardware/Motors/ecmcEL7037-Motor-Phytron-VSS-80.200.5.cmd
> +#-d   \brief hardware script for EL7037-Motor-Phytron-VSS-52.200.2.5
VSS-80.200.5

2023-09-13 21:36 UTC, kivel commented on hardware/Motors/ecmcEL7037-Motor-Phytron-VSS-80.200.5.cmd
> +#-d   \details Parametrization of EL7037 for motor Phytron VSS 52.200.2.5
VSS-80.200.5

2023-09-13 21:36 UTC, kivel commented on hardware/Motors/ecmcEL7041-Motor-Phytron-VSS-80.200.5.cmd
> +#-d   \brief hardware script for EL7041-Motor-Phytron-VSS-52.200.2.5
VSS-80.200.5

2023-09-13 21:36 UTC, kivel commented on hardware/Motors/ecmcEL7041-Motor-Phytron-VSS-80.200.5.cmd
> +#-d   \details Parametrization of EL7041 for motor Phytron VSS 52.200.2.5
VSS-80.200.5

2023-09-13 21:36 UTC, kivel commented on hardware/Motors/ecmcEL7047-Motor-Phytron-VSS-80.200.5.cmd
> +#-d   \brief hardware script for EL7047-Motor-Phytron-VSS-52.200.2.5
VSS-80.200.5

2023-09-13 21:36 UTC, kivel commented on hardware/Motors/ecmcEL7047-Motor-Phytron-VSS-80.200.5.cmd
> +#-d   \details Parametrization of EL7047 for motor Phytron VSS 52.200.2.5
VSS-80.200.5

2023-09-15 08:32 UTC, cdn-lnk commented
Hi @anderssandstrom and @kivel ,

Guess I was having a bad day when I pressed the push button. 😅
It should be all fixed now, thanks for catching that.

2023-09-15 15:08 UTC, kivel commented
@cdn-lnk no worries, that's what reviews are for.

2023-09-15 15:08 UTC, merged